# Generated by Django 5.0.1 on 2024-02-03 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at date')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Deleted at date')),
                ('name', models.TextField()),
                ('birth_date', models.DateField()),
                ('biography', models.TextField()),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at date')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Deleted at date')),
                ('title', models.TextField()),
                ('pages', models.IntegerField()),
                ('isbn_code', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author_crud.author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at date')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Deleted at date')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author_crud.book')),
            ],
            options={
                'verbose_name': 'Reviews',
                'db_table': 'reviews',
            },
        ),
    ]
